### ISSUE TITLE
0.6.0 release

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/cosas#37]
@laughedelic I want to release 0.6.0 ASAP. What's left?

**Comment by eparejatobes** [comment]
#34 and #32 are already merged. With respect to #32, it'd be good to investigate whether spire already has instances for our use here

- [Spire std Map](https://github.com/non/spire/blob/master/core/src/main/scala/spire/std/map.scala)
- [Spire std Seq](https://github.com/non/spire/blob/master/core/src/main/scala/spire/std/seq.scala)

**Comment by laughedelic** [comment]
Cool, great, nice! :+1: 
What's left?

**Comment by eparejatobes** [comment]
If you want (but not essential) 

- take a look at the Spire stuff (what I said above)
- we should merge #39 
- rename tests stuff following the convention in `src/main`

**Comment by laughedelic** [comment]
What's up here?

**Comment by eparejatobes** [comment]
@laughedelic I'm merging #39 and releasing 0.6.0

**Comment by laughedelic** [comment]
:+1:

**Comment by laughedelic** [comment]
@eparejatobes please, make this release. all the new cats-stuff is definitely for the next time and we need something stable for statika & scarph

**Comment by laughedelic** [comment]
done
