### ISSUE TITLE
Weak tagging

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/cosas#65]
I started updating scarph to cosas-0.7 and remembered that we've "fixed" `:=` method so that it has a bound on the value type `<: Tpe#Raw`.
But in scarph objects/morphisms don't have any fixed raw bound. That's evals of an implementation who define what the raw types are. I know that
- I can set explicitly `type Raw = Any`, but then in all the abstract evals I need an explicit bounding of the raw input/output types _for nothing_.
- I can use `new Denotes[V, T](v: V)` constructor, which is super inconvenient

So I just want a `:=` version without any bound, for creating denotations (which itself doesn't have any bound on the `Value` type member)

**Comment by eparejatobes** [comment]
*If* your type has `Raw = Any` you don't need any explicit bound.

**Comment by eparejatobes** [comment]
related: 030650c

**Comment by laughedelic** [comment]
well, vertices/edges/morphisms have Any, and property vals have some bound "/

**Comment by eparejatobes** [comment]
Denotations do have a bound on the `Value` type, and in the case of `Raw` being `Any` you don't need any bound. Closing, please reopen if there's something else I can do here.
