### ISSUE TITLE
Types and denotations improvements

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/cosas#66]
I want to discuss here a more uniform approach to types and denotations. If possible, this should go in `1.0`. In general, I would like to have operations on types with the corresponding reflection on denotations, guaranteeing functoriality in a structural way. For example:

#### Product of types

Given that bounded covariant `KList`s work, we can

1. define a product of types with their `Raw` built recursively
2. denotations of that product type use subtypes of `Raw` which correspond to a product of denotations of the types forming the product

This way a record would be essentially equivalent to a product of different types. We'd also have no need for properties.

#### Function types

Essentially the same. We can make a type `X ==> Y <: AnyType` for `X,Y <: AnyType` with `Raw` a `DepFn1[X#Raw,Y#Raw]`.

**Comment by eparejatobes** [comment]
For example:

``` scala
trait AnyProductType extends AnyType {

  type Types <: AnyKList { type Bound = AnyType }
  val types: Types

  type Raw <: AnyKList { type Bound = AnyDenotation }
}

case object AnyProductType {

  implicit def productTypeSyntax[L <: AnyProductType](l: L): AnyProductTypeSyntax[L] =
    AnyProductTypeSyntax(l)
}

case object EmptyProductType extends AnyProductType {

  type Types = KNil[AnyType]
  val  types = KNil[AnyType]

  type Raw = KNil[AnyDenotation]

  val label: String = "□"
}

case class :×:[H <: AnyType, T <: AnyProductType](val head: H, val tail: T) extends AnyProductType {

  type Types = H :: T#Types
  val  types: Types = head :: tail.types

  type Raw = AnyDenotationOf[H] :: T#Raw

  lazy val label: String = s"${head.label} :×: ${tail.label}"
}

case class AnyProductTypeSyntax[L <: AnyProductType](val l: L) extends AnyVal {

  def :×:[H <: AnyType, T <: AnyProductType](h: H): H :×: L =
    new :×:(h,l)
}
```

**Comment by eparejatobes** [comment]
and using that:

``` scala
  case object a extends AnyType { type Raw = Any; val label = "a" }
  case object b extends AnyType { type Raw = Int; val label = "b" }

  val ab = a :×: b :×: EmptyProductType

  implicitly[
    ab.Raw =:= (
      AnyDenotationOf[a.type] :: 
      AnyDenotationOf[b.type] :: 
      KNil[AnyDenotation]
    )
  ]

  val z = ab := (
    (a := "hola!")  :: 
    (b := 2)        :: KNil[AnyDenotation]
  )
```

**Comment by laughedelic** [comment]
Nice! :+1: 
How about projections? shouldn't it be a (bounded) typeset inside, instead of a klist?

**Comment by eparejatobes** [comment]
projections?

**Comment by laughedelic** [comment]
btw, if we have typesets and klists, we could have kind of multisets..

**Comment by laughedelic** [comment]
> projections?

lookup/get by the type type

**Comment by eparejatobes** [comment]
Most of this is already in master. I will start moving records and properties to the new approach

**Comment by eparejatobes** [comment]
actually this needs KSets, so wating for it

**Comment by eparejatobes** [comment]
Closing this as it is already in master. I'll open a new issue for records
